// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMm7JXy2cZGgSNt4avXV4xACI-m-XuLtM',
    appId: '1:564595847008:android:5010fcedf5d393243c3805',
    messagingSenderId: '564595847008',
    projectId: 'dhsys-ab9af',
    databaseURL: 'https://dhsys-ab9af-default-rtdb.firebaseio.com',
    storageBucket: 'dhsys-ab9af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGP4xzh8a2yZKvxF5_iwIbJ5dYneQ3sMI',
    appId: '1:564595847008:ios:3f72f1396a17158a3c3805',
    messagingSenderId: '564595847008',
    projectId: 'dhsys-ab9af',
    databaseURL: 'https://dhsys-ab9af-default-rtdb.firebaseio.com',
    storageBucket: 'dhsys-ab9af.firebasestorage.app',
    iosBundleId: 'com.aviation.dhsys',
  );
}
